#pragma once
// Generated from LiquidParticleCleanup.cu, CUDA 12.8 compute_75.
inline constexpr char LiquidParticleCleanupPtx[] = R"LIQUID_PTX(
//
// Generated by NVIDIA NVVM Compiler
//
// Compiler Build ID: CL-35583870
// Cuda compilation tools, release 12.8, V12.8.93
// Based on NVVM 7.0.1
//

.version 8.7
.target sm_75
.address_size 64

	// .globl	compactLiquidParticles
// _ZZ22compactLiquidParticlesE6prefix has been demoted
// _ZZ22compactLiquidParticlesE10outputBase has been demoted

.visible .entry compactLiquidParticles(
	.param .u64 compactLiquidParticles_param_0,
	.param .u64 compactLiquidParticles_param_1,
	.param .u64 compactLiquidParticles_param_2,
	.param .u64 compactLiquidParticles_param_3,
	.param .u64 compactLiquidParticles_param_4,
	.param .u64 compactLiquidParticles_param_5,
	.param .u64 compactLiquidParticles_param_6,
	.param .u32 compactLiquidParticles_param_7,
	.param .f32 compactLiquidParticles_param_8,
	.param .u64 compactLiquidParticles_param_9,
	.param .u64 compactLiquidParticles_param_10
)
{
	.reg .pred 	%p<21>;
	.reg .f32 	%f<106>;
	.reg .b32 	%r<148>;
	.reg .b64 	%rd<35>;
	// demoted variable
	.shared .align 4 .b8 _ZZ22compactLiquidParticlesE6prefix[1024];
	// demoted variable
	.shared .align 4 .u32 _ZZ22compactLiquidParticlesE10outputBase;

	ld.param.u64 	%rd3, [compactLiquidParticles_param_0];
	ld.param.u64 	%rd4, [compactLiquidParticles_param_1];
	ld.param.u64 	%rd5, [compactLiquidParticles_param_2];
	ld.param.u64 	%rd6, [compactLiquidParticles_param_3];
	ld.param.u64 	%rd7, [compactLiquidParticles_param_4];
	ld.param.u64 	%rd8, [compactLiquidParticles_param_5];
	ld.param.u64 	%rd9, [compactLiquidParticles_param_6];
	ld.param.u32 	%r21, [compactLiquidParticles_param_7];
	ld.param.f32 	%f74, [compactLiquidParticles_param_8];
	ld.param.u64 	%rd10, [compactLiquidParticles_param_9];
	ld.param.u64 	%rd11, [compactLiquidParticles_param_10];
	mov.u32 	%r22, %tid.x;
	mov.u32 	%r23, %ntid.x;
	mov.u32 	%r24, %ctaid.x;
	mad.lo.s32 	%r1, %r24, %r23, %r22;
	setp.ge.u32 	%p1, %r1, %r21;
	mov.u32 	%r140, 0;
	mov.f32 	%f98, 0f00000000;
	mov.f32 	%f99, %f98;
	mov.f32 	%f100, %f98;
	mov.f32 	%f101, %f98;
	mov.f32 	%f102, %f98;
	mov.f32 	%f103, %f98;
	mov.f32 	%f104, %f98;
	mov.f32 	%f105, %f98;
	mov.u32 	%r139, %r140;
	@%p1 bra 	$L__BB0_9;

	cvta.to.global.u64 	%rd12, %rd3;
	mul.wide.u32 	%rd13, %r1, 16;
	add.s64 	%rd14, %rd12, %rd13;
	ld.global.v4.f32 	{%f101, %f100, %f99, %f98}, [%rd14];
	cvta.to.global.u64 	%rd15, %rd4;
	add.s64 	%rd16, %rd15, %rd13;
	ld.global.v4.f32 	{%f105, %f104, %f103, %f102}, [%rd16];
	abs.f32 	%f91, %f101;
	setp.geu.f32 	%p2, %f91, 0f7F800000;
	@%p2 bra 	$L__BB0_9;

	abs.f32 	%f92, %f100;
	setp.geu.f32 	%p3, %f92, 0f7F800000;
	mov.u32 	%r139, %r140;
	@%p3 bra 	$L__BB0_9;

	abs.f32 	%f93, %f99;
	setp.geu.f32 	%p4, %f93, 0f7F800000;
	mov.u32 	%r139, %r140;
	@%p4 bra 	$L__BB0_9;

	abs.f32 	%f94, %f98;
	setp.geu.f32 	%p5, %f94, 0f7F800000;
	mov.u32 	%r139, %r140;
	@%p5 bra 	$L__BB0_9;

	abs.f32 	%f95, %f105;
	setp.geu.f32 	%p6, %f95, 0f7F800000;
	mov.u32 	%r139, %r140;
	@%p6 bra 	$L__BB0_9;

	abs.f32 	%f96, %f104;
	setp.geu.f32 	%p7, %f96, 0f7F800000;
	mov.u32 	%r139, %r140;
	@%p7 bra 	$L__BB0_9;

	abs.f32 	%f97, %f103;
	setp.geu.f32 	%p8, %f97, 0f7F800000;
	mov.u32 	%r139, %r140;
	@%p8 bra 	$L__BB0_9;

	setp.ge.f32 	%p9, %f100, %f74;
	selp.u32 	%r139, 1, 0, %p9;

$L__BB0_9:
	shl.b32 	%r34, %r22, 2;
	mov.u32 	%r35, _ZZ22compactLiquidParticlesE6prefix;
	add.s32 	%r36, %r35, %r34;
	st.shared.u32 	[%r36], %r139;
	bar.sync 	0;
	setp.eq.s32 	%p10, %r22, 0;
	@%p10 bra 	$L__BB0_11;

	ld.shared.u32 	%r140, [%r36+-4];

$L__BB0_11:
	bar.sync 	0;
	ld.shared.u32 	%r46, [%r36];
	mov.u32 	%r142, 0;
	add.s32 	%r47, %r46, %r140;
	st.shared.u32 	[%r36], %r47;
	bar.sync 	0;
	setp.lt.u32 	%p11, %r22, 2;
	mov.u32 	%r141, %r142;
	@%p11 bra 	$L__BB0_13;

	ld.shared.u32 	%r141, [%r36+-8];

$L__BB0_13:
	bar.sync 	0;
	ld.shared.u32 	%r57, [%r36];
	add.s32 	%r58, %r57, %r141;
	st.shared.u32 	[%r36], %r58;
	bar.sync 	0;
	setp.lt.u32 	%p12, %r22, 4;
	@%p12 bra 	$L__BB0_15;

	ld.shared.u32 	%r142, [%r36+-16];

$L__BB0_15:
	bar.sync 	0;
	ld.shared.u32 	%r68, [%r36];
	mov.u32 	%r144, 0;
	add.s32 	%r69, %r68, %r142;
	st.shared.u32 	[%r36], %r69;
	bar.sync 	0;
	setp.lt.u32 	%p13, %r22, 8;
	mov.u32 	%r143, %r144;
	@%p13 bra 	$L__BB0_17;

	ld.shared.u32 	%r143, [%r36+-32];

$L__BB0_17:
	bar.sync 	0;
	ld.shared.u32 	%r79, [%r36];
	add.s32 	%r80, %r79, %r143;
	st.shared.u32 	[%r36], %r80;
	bar.sync 	0;
	setp.lt.u32 	%p14, %r22, 16;
	@%p14 bra 	$L__BB0_19;

	ld.shared.u32 	%r144, [%r36+-64];

$L__BB0_19:
	bar.sync 	0;
	ld.shared.u32 	%r90, [%r36];
	mov.u32 	%r146, 0;
	add.s32 	%r91, %r90, %r144;
	st.shared.u32 	[%r36], %r91;
	bar.sync 	0;
	setp.lt.u32 	%p15, %r22, 32;
	mov.u32 	%r145, %r146;
	@%p15 bra 	$L__BB0_21;

	ld.shared.u32 	%r145, [%r36+-128];

$L__BB0_21:
	bar.sync 	0;
	ld.shared.u32 	%r101, [%r36];
	add.s32 	%r102, %r101, %r145;
	st.shared.u32 	[%r36], %r102;
	bar.sync 	0;
	setp.lt.u32 	%p16, %r22, 64;
	@%p16 bra 	$L__BB0_23;

	ld.shared.u32 	%r146, [%r36+-256];

$L__BB0_23:
	bar.sync 	0;
	ld.shared.u32 	%r112, [%r36];
	mov.u32 	%r147, 0;
	add.s32 	%r113, %r112, %r146;
	st.shared.u32 	[%r36], %r113;
	bar.sync 	0;
	setp.lt.u32 	%p17, %r22, 128;
	@%p17 bra 	$L__BB0_25;

	ld.shared.u32 	%r147, [%r36+-512];

$L__BB0_25:
	setp.ne.s32 	%p18, %r22, 0;
	bar.sync 	0;
	ld.shared.u32 	%r122, [%r36];
	add.s32 	%r123, %r122, %r147;
	st.shared.u32 	[%r36], %r123;
	bar.sync 	0;
	@%p18 bra 	$L__BB0_27;

	ld.shared.u32 	%r124, [_ZZ22compactLiquidParticlesE6prefix+1020];
	cvta.to.global.u64 	%rd17, %rd9;
	atom.global.add.u32 	%r125, [%rd17], %r124;
	st.shared.u32 	[_ZZ22compactLiquidParticlesE10outputBase], %r125;

$L__BB0_27:
	bar.sync 	0;
	setp.eq.s32 	%p19, %r139, 0;
	@%p19 bra 	$L__BB0_30;

	ld.shared.u32 	%r126, [_ZZ22compactLiquidParticlesE10outputBase];
	ld.shared.u32 	%r131, [%r36];
	add.s32 	%r132, %r126, %r131;
	add.s32 	%r133, %r132, -1;
	cvt.u64.u32 	%rd1, %r133;
	cvta.to.global.u64 	%rd18, %rd6;
	mul.wide.u32 	%rd19, %r133, 16;
	add.s64 	%rd20, %rd18, %rd19;
	st.global.v4.f32 	[%rd20], {%f101, %f100, %f99, %f98};
	cvta.to.global.u64 	%rd21, %rd7;
	add.s64 	%rd22, %rd21, %rd19;
	st.global.v4.f32 	[%rd22], {%f105, %f104, %f103, %f102};
	cvt.u64.u32 	%rd2, %r1;
	cvta.to.global.u64 	%rd23, %rd5;
	mul.wide.u32 	%rd24, %r1, 4;
	add.s64 	%rd25, %rd23, %rd24;
	ld.global.u32 	%r137, [%rd25];
	cvta.to.global.u64 	%rd26, %rd8;
	mul.wide.u32 	%rd27, %r133, 4;
	add.s64 	%rd28, %rd26, %rd27;
	st.global.u32 	[%rd28], %r137;
	setp.eq.s64 	%p20, %rd10, 0;
	@%p20 bra 	$L__BB0_30;

	cvta.to.global.u64 	%rd29, %rd10;
	shl.b64 	%rd30, %rd2, 2;
	add.s64 	%rd31, %rd29, %rd30;
	ld.global.u32 	%r138, [%rd31];
	cvta.to.global.u64 	%rd32, %rd11;
	shl.b64 	%rd33, %rd1, 2;
	add.s64 	%rd34, %rd32, %rd33;
	st.global.u32 	[%rd34], %r138;

$L__BB0_30:
	ret;

}


)LIQUID_PTX";
