#pragma once
// Generated from LiquidParticleCleanup.cu using CUDA 12.8, compute_75.
inline constexpr char LiquidParticleCleanupPtx[] = R"LIQUID_PTX(
//
// Generated by NVIDIA NVVM Compiler
//
// Compiler Build ID: CL-35583870
// Cuda compilation tools, release 12.8, V12.8.93
// Based on NVVM 7.0.1
//

.version 8.7
.target sm_75
.address_size 64

	// .globl	compactLiquidParticles
// _ZZ22compactLiquidParticlesE6prefix has been demoted
// _ZZ22compactLiquidParticlesE10outputBase has been demoted

.visible .entry compactLiquidParticles(
	.param .u64 compactLiquidParticles_param_0,
	.param .u64 compactLiquidParticles_param_1,
	.param .u64 compactLiquidParticles_param_2,
	.param .u64 compactLiquidParticles_param_3,
	.param .u64 compactLiquidParticles_param_4,
	.param .u64 compactLiquidParticles_param_5,
	.param .u64 compactLiquidParticles_param_6,
	.param .u32 compactLiquidParticles_param_7,
	.param .f32 compactLiquidParticles_param_8
)
{
	.reg .pred 	%p<20>;
	.reg .f32 	%f<92>;
	.reg .b32 	%r<147>;
	.reg .b64 	%rd<25>;
	// demoted variable
	.shared .align 4 .b8 _ZZ22compactLiquidParticlesE6prefix[1024];
	// demoted variable
	.shared .align 4 .u32 _ZZ22compactLiquidParticlesE10outputBase;

	ld.param.u64 	%rd1, [compactLiquidParticles_param_0];
	ld.param.u64 	%rd2, [compactLiquidParticles_param_1];
	ld.param.u64 	%rd3, [compactLiquidParticles_param_2];
	ld.param.u64 	%rd4, [compactLiquidParticles_param_3];
	ld.param.u64 	%rd5, [compactLiquidParticles_param_4];
	ld.param.u64 	%rd6, [compactLiquidParticles_param_5];
	ld.param.u64 	%rd7, [compactLiquidParticles_param_6];
	ld.param.u32 	%r21, [compactLiquidParticles_param_7];
	ld.param.f32 	%f60, [compactLiquidParticles_param_8];
	mov.u32 	%r22, %tid.x;
	mov.u32 	%r23, %ntid.x;
	mov.u32 	%r24, %ctaid.x;
	mad.lo.s32 	%r1, %r24, %r23, %r22;
	setp.ge.u32 	%p1, %r1, %r21;
	mov.u32 	%r139, 0;
	mov.f32 	%f84, 0f00000000;
	mov.f32 	%f85, %f84;
	mov.f32 	%f86, %f84;
	mov.f32 	%f87, %f84;
	mov.f32 	%f88, %f84;
	mov.f32 	%f89, %f84;
	mov.f32 	%f90, %f84;
	mov.f32 	%f91, %f84;
	mov.u32 	%r138, %r139;
	@%p1 bra 	$L__BB0_9;

	cvta.to.global.u64 	%rd8, %rd1;
	mul.wide.u32 	%rd9, %r1, 16;
	add.s64 	%rd10, %rd8, %rd9;
	ld.global.v4.f32 	{%f87, %f86, %f85, %f84}, [%rd10];
	cvta.to.global.u64 	%rd11, %rd2;
	add.s64 	%rd12, %rd11, %rd9;
	ld.global.v4.f32 	{%f91, %f90, %f89, %f88}, [%rd12];
	abs.f32 	%f77, %f87;
	setp.geu.f32 	%p2, %f77, 0f7F800000;
	@%p2 bra 	$L__BB0_9;

	abs.f32 	%f78, %f86;
	setp.geu.f32 	%p3, %f78, 0f7F800000;
	mov.u32 	%r138, %r139;
	@%p3 bra 	$L__BB0_9;

	abs.f32 	%f79, %f85;
	setp.geu.f32 	%p4, %f79, 0f7F800000;
	mov.u32 	%r138, %r139;
	@%p4 bra 	$L__BB0_9;

	abs.f32 	%f80, %f84;
	setp.geu.f32 	%p5, %f80, 0f7F800000;
	mov.u32 	%r138, %r139;
	@%p5 bra 	$L__BB0_9;

	abs.f32 	%f81, %f91;
	setp.geu.f32 	%p6, %f81, 0f7F800000;
	mov.u32 	%r138, %r139;
	@%p6 bra 	$L__BB0_9;

	abs.f32 	%f82, %f90;
	setp.geu.f32 	%p7, %f82, 0f7F800000;
	mov.u32 	%r138, %r139;
	@%p7 bra 	$L__BB0_9;

	abs.f32 	%f83, %f89;
	setp.geu.f32 	%p8, %f83, 0f7F800000;
	mov.u32 	%r138, %r139;
	@%p8 bra 	$L__BB0_9;

	setp.ge.f32 	%p9, %f86, %f60;
	selp.u32 	%r138, 1, 0, %p9;

$L__BB0_9:
	shl.b32 	%r34, %r22, 2;
	mov.u32 	%r35, _ZZ22compactLiquidParticlesE6prefix;
	add.s32 	%r36, %r35, %r34;
	st.shared.u32 	[%r36], %r138;
	bar.sync 	0;
	setp.eq.s32 	%p10, %r22, 0;
	@%p10 bra 	$L__BB0_11;

	ld.shared.u32 	%r139, [%r36+-4];

$L__BB0_11:
	bar.sync 	0;
	ld.shared.u32 	%r46, [%r36];
	mov.u32 	%r141, 0;
	add.s32 	%r47, %r46, %r139;
	st.shared.u32 	[%r36], %r47;
	bar.sync 	0;
	setp.lt.u32 	%p11, %r22, 2;
	mov.u32 	%r140, %r141;
	@%p11 bra 	$L__BB0_13;

	ld.shared.u32 	%r140, [%r36+-8];

$L__BB0_13:
	bar.sync 	0;
	ld.shared.u32 	%r57, [%r36];
	add.s32 	%r58, %r57, %r140;
	st.shared.u32 	[%r36], %r58;
	bar.sync 	0;
	setp.lt.u32 	%p12, %r22, 4;
	@%p12 bra 	$L__BB0_15;

	ld.shared.u32 	%r141, [%r36+-16];

$L__BB0_15:
	bar.sync 	0;
	ld.shared.u32 	%r68, [%r36];
	mov.u32 	%r143, 0;
	add.s32 	%r69, %r68, %r141;
	st.shared.u32 	[%r36], %r69;
	bar.sync 	0;
	setp.lt.u32 	%p13, %r22, 8;
	mov.u32 	%r142, %r143;
	@%p13 bra 	$L__BB0_17;

	ld.shared.u32 	%r142, [%r36+-32];

$L__BB0_17:
	bar.sync 	0;
	ld.shared.u32 	%r79, [%r36];
	add.s32 	%r80, %r79, %r142;
	st.shared.u32 	[%r36], %r80;
	bar.sync 	0;
	setp.lt.u32 	%p14, %r22, 16;
	@%p14 bra 	$L__BB0_19;

	ld.shared.u32 	%r143, [%r36+-64];

$L__BB0_19:
	bar.sync 	0;
	ld.shared.u32 	%r90, [%r36];
	mov.u32 	%r145, 0;
	add.s32 	%r91, %r90, %r143;
	st.shared.u32 	[%r36], %r91;
	bar.sync 	0;
	setp.lt.u32 	%p15, %r22, 32;
	mov.u32 	%r144, %r145;
	@%p15 bra 	$L__BB0_21;

	ld.shared.u32 	%r144, [%r36+-128];

$L__BB0_21:
	bar.sync 	0;
	ld.shared.u32 	%r101, [%r36];
	add.s32 	%r102, %r101, %r144;
	st.shared.u32 	[%r36], %r102;
	bar.sync 	0;
	setp.lt.u32 	%p16, %r22, 64;
	@%p16 bra 	$L__BB0_23;

	ld.shared.u32 	%r145, [%r36+-256];

$L__BB0_23:
	bar.sync 	0;
	ld.shared.u32 	%r112, [%r36];
	mov.u32 	%r146, 0;
	add.s32 	%r113, %r112, %r145;
	st.shared.u32 	[%r36], %r113;
	bar.sync 	0;
	setp.lt.u32 	%p17, %r22, 128;
	@%p17 bra 	$L__BB0_25;

	ld.shared.u32 	%r146, [%r36+-512];

$L__BB0_25:
	setp.ne.s32 	%p18, %r22, 0;
	bar.sync 	0;
	ld.shared.u32 	%r122, [%r36];
	add.s32 	%r123, %r122, %r146;
	st.shared.u32 	[%r36], %r123;
	bar.sync 	0;
	@%p18 bra 	$L__BB0_27;

	ld.shared.u32 	%r124, [_ZZ22compactLiquidParticlesE6prefix+1020];
	cvta.to.global.u64 	%rd13, %rd7;
	atom.global.add.u32 	%r125, [%rd13], %r124;
	st.shared.u32 	[_ZZ22compactLiquidParticlesE10outputBase], %r125;

$L__BB0_27:
	bar.sync 	0;
	setp.eq.s32 	%p19, %r138, 0;
	@%p19 bra 	$L__BB0_29;

	ld.shared.u32 	%r126, [_ZZ22compactLiquidParticlesE10outputBase];
	ld.shared.u32 	%r131, [%r36];
	add.s32 	%r132, %r126, %r131;
	add.s32 	%r133, %r132, -1;
	cvta.to.global.u64 	%rd14, %rd4;
	mul.wide.u32 	%rd15, %r133, 16;
	add.s64 	%rd16, %rd14, %rd15;
	st.global.v4.f32 	[%rd16], {%f87, %f86, %f85, %f84};
	cvta.to.global.u64 	%rd17, %rd5;
	add.s64 	%rd18, %rd17, %rd15;
	st.global.v4.f32 	[%rd18], {%f91, %f90, %f89, %f88};
	cvta.to.global.u64 	%rd19, %rd3;
	mul.wide.u32 	%rd20, %r1, 4;
	add.s64 	%rd21, %rd19, %rd20;
	ld.global.u32 	%r137, [%rd21];
	cvta.to.global.u64 	%rd22, %rd6;
	mul.wide.u32 	%rd23, %r133, 4;
	add.s64 	%rd24, %rd22, %rd23;
	st.global.u32 	[%rd24], %r137;

$L__BB0_29:
	ret;

}

)LIQUID_PTX";
